<?php

namespace App\Http\Controllers;

use App\Models\PresentationSlide;
use Illuminate\Http\Request;
use App\Services\GeminiService;

class PresentationController extends Controller
{
    public function index()
    {
        $slides = PresentationSlide::where('is_active', true)->orderBy('order')->get();
        return view('presentation', compact('slides'));
    }

    public function manage()
    {
        $slides = PresentationSlide::orderBy('order')->get();
        return view('presentation.manage', compact('slides'));
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'subtitle' => 'nullable|string|max:255',
            'content' => 'nullable|string',
            'layout_type' => 'required|string|in:standard,center,grid,profile',
            'bg_color' => 'nullable|string|max:20',
            'order' => 'required|integer',
        ]);

        $validated['is_active'] = $request->boolean('is_active', true);

        PresentationSlide::create($validated);
        return back()->with('success', 'Slide added successfully.');
    }

    public function update(Request $request, PresentationSlide $slide)
    {
        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'subtitle' => 'nullable|string|max:255',
            'content' => 'nullable|string',
            'layout_type' => 'required|string|in:standard,center,grid,profile',
            'bg_color' => 'nullable|string|max:20',
            'order' => 'required|integer',
        ]);

        $validated['is_active'] = $request->boolean('is_active');

        $slide->update($validated);
        return back()->with('success', 'Slide updated successfully.');
    }

    public function reorder(Request $request)
    {
        $request->validate([
            'order' => 'required|array',
            'order.*' => 'required|integer|exists:presentation_slides,id'
        ]);

        foreach ($request->order as $index => $id) {
            PresentationSlide::where('id', $id)->update(['order' => $index + 1]);
        }

        return response()->json(['success' => true]);
    }

    public function suggest(Request $request, GeminiService $gemini)
    {
        $topic = $request->input('topic', 'interior design');
        $prompt = "Generate a professional presentation slide in JSON format with 'title', 'subtitle', and 'content' (markdown) keys. Topic: {$topic}. Keep it concise and premium.";

        $suggestion = $gemini->generateSlideContent($prompt);

        return response()->json($suggestion ?: [
            'title' => 'Suggested Title',
            'subtitle' => 'Professional Presentation',
            'content' => 'Content generated by AI for your slide.'
        ]);
    }

    public function destroy(PresentationSlide $slide)
    {
        $slide->delete();
        return back()->with('success', 'Slide deleted successfully.');
    }
}